### PR TITLE
List Binder

### PR DESCRIPTION
**Pull request by paulis**
List Binder that binds a values as an injectable list. 

Usage:
listBinder.Bind<IMyClass>().To<MyClass>();

[Inject]
public IList<IMyClass> myInstances;

Internally list binder uses injection binder to populate the list with instances. Expanded InjectionBinder with a dedicated method for instantiating list bindings (performListInjection)

See TestListBinder for reference

TODO named list bindings.

### CODE REVIEW

**Comment by mr-robert** [comment]
Please review this :)

**Comment by WillzZz** [comment]
Please re-open this against strange-ioc

**Comment by eransh22** [comment]
Was this feature merged already?

**Comment by WillzZz** [comment]
It was not.

**Comment by eransh22** [comment]
Can I ask why wasn't it merged?

**Comment by WillzZz** [comment]
It's been a while, but Marc and I had a thorough discussion about it when I visited and we decided against it. Ultimately, this solves a very specific use case, and that was my argument against it. I think it's pretty cool, though!

**Pull request closed without merging**
